### ISSUE TITLE
drawRect() - incomplete filling

### ISSUE THREAD

**Issue by mchobby** [ropod7/pyboard_drive#12]
Reducing the border size in 03b_rgbTo565.py sample highlight a filling issue.
Changing the line

`l.drawRect( 0, yStart, 240, yHeight, aColor, border=3, fillcolor=aColor )`

to

`l.drawRect( 0, yStart, 240, yHeight, aColor, border=1, fillcolor=aColor )`

Produce the following result (not filled enough?) whereas everything looks perfect with a ticker border (3 pixels).

![img_7387](https://cloud.githubusercontent.com/assets/2701466/14245127/73d5bba0-fa5f-11e5-9baa-f22dbd837099.JPG)

**Comment by ropod7** [comment]
I will check.

**Comment by mchobby** [comment]
I did downloaded the latest version of LCD. And issue is still present.

**Comment by ropod7** [comment]
Should be fixed.

**Comment by mchobby** [comment]
Work great :-)
