### ISSUE TITLE
Second suggest...

### ISSUE THREAD

**Issue by mchobby** [ropod7/pyboard_drive#2]
# proposal 1

Replacing the list in color definition by tuples (immutable, so maybe less memory consuming) and maybe by following the RGB888 color definition.
BLACK       = [0,  0,  0 ]  with BLACK = (0,0,0)
# proposal 2

Use a function to transform RGB888 color (user friendly) to to RGR565 color (TFT friendly)

def rgb565_color( color ):
   """ Transform a rgb888 color tuple to rgb565 color tuple """ 
   r,g,b = color
   return ( int(float(r) / 255 \* 31), int(float(g) / 255 \* 63) , int(float(b) / 255 \* 31) )

**Comment by ropod7** [comment]
It is good idea.
I think to change color definition structure to 16 bit HEX double word, as 0xFFFF for white. That gives to us less bit operations. Bit operations must be realized as in your "proposal 2" and others (gradient generation, etc)
Now it's just visually and user friendly.

Thanks for feedback!
