### ISSUE TITLE
fonts.py - suggest?

### ISSUE THREAD

**Issue by mchobby** [ropod7/pyboard_drive#3]
In the fonts declaration, you are using the chXXX as key of the dictionnary.
Eg: ch32

Using the ascii numerical value (32) as dictionary key (instead of ch32 which is a string) could be more efficient (in term of memory usage)? To be confirmed.
This would also requires less code to convert a character in a string to a it's font value.

May I suggest something like this:
Arial_14 = {}
Arial_14['width'] = 0x0D # width
Arial_14['height'] = 0x0E # height
Arial_14[32] = (0x4000,)  # <space> 0x20
Arial_14[33] = (0x4BFC,)  # 33 !
Arial_14[34] = (0x403c, 0x4000, 0x403c)  # 34 "
Arial_14[35] = (0x4120, 0x4f20, 0x41f0, 0x412c, 0x4f20, 0x41f0, 0x412c, 0x4120)  # 35 #

**Comment by ropod7** [comment]
It is done,
And now it's classificated
