### ISSUE TITLE
Suggestion for drawCircle()

### ISSUE THREAD

**Issue by mchobby** [ropod7/pyboard_drive#6]
I would suggest to add a start_degree to the drawCircle function.

```
def drawCircle(self, x, y, radius, color, border=1, start_degree=0, degrees=360):
```

By adding a start_degree then it would be possible to draw "section of circle".
This would allow drawing of rounded rectangle (for nice buttons drawing ;-) ).

Kind regards,
Dominique

**Comment by ropod7** [comment]
Yes, I was looking forward to with this feature. Now I remember to set it in drawCircle.

**Comment by ropod7** [comment]
Done. Thanks.
