### ISSUE TITLE
some french documentation available

### ISSUE THREAD

**Issue by mchobby** [ropod7/pyboard_drive#7]
Hi Roman, 

I did prepared a [french tutorial](http://wiki.mchobby.be/index.php?title=MicroPython-ILI9341-Brancher) and wiring with the Adafruit Arduino Touch Shield (powered with ILI9341). 
Running your fabulous driver.

Nice Oriented Object implementation... very interesting approach.

**Comment by ropod7** [comment]
Amazing!
